config/routes.rb
HaikuVillage::Application.routes.draw do
  resources :authors do
    member do
      get :friends
    end

    resources :subjects, controller: 'authors/subjects'
  end
  match 'signup' => 'authors#new', as: 'signup'

  match 'autocomplete/subject' => 'subjects#autocomplete'

  resources :subjects do
    collection do
      get :suggest
    end
  end

  resources :haikus, path: 'haiku' do
    collection do
      get :search
    end
  end

  resources :conversations
  resources :messages
  resources :friends
  resources :favorites

  resources :password_resets, path: 'forgot'

  controller 'public' do
    match 'about' => :about, as: :about
    match 'register' => :register, as: :register
    match 'feedback' => :feedback, as: :feedback
  end

  resource :session

  controller 'sessions' do
    match 'login' => :new, as: 'login'
    match 'logout' => :destroy, as: 'logout'
  end

  match   'settings(/:action)' => 'profile', as: :profile
  match   'journal(/:action)' => 'journal', as: :journal

  match 'google_gadget' => 'public#google_gadget', defaults: { format: 'xml' }, as: 'google_gadget'
  match 'syllables' => 'syllables#index'

  root to: 'public#index'
end

app/models/haiku.rb
require 'haiku/line'

class Haiku < ActiveRecord::Base
  include Haiku::Conversational
  
  belongs_to :author
  belongs_to :subject
  has_many :favorites, :dependent => :delete_all
  has_many :happy_authors, :through => :favorites, :source => :author
    
  scope :recent, order('haikus.id desc').includes([:conversation, :author])
  
  after_create do |haiku|
    Author.update_counters(haiku.author_id, :haikus_count_week => 1, :haikus_count_total => 1)
    Subject.update_counters(haiku.subject_id, :haikus_count_week => 1, :haikus_count_total => 1) if haiku.subject_id
    haiku.author.update_attribute(:latest_haiku_id, haiku.id)
  end
  
  before_destroy do |haiku|
    Author.update_counters(haiku.author_id, :haikus_count_total => -1)
    Subject.update_counters(haiku.subject_id, :haikus_count_total => -1) if haiku.subject_id
  end
  
  validates_presence_of :text, :on => :create
  validate :valid_syllables?, on: :create

  class << self
    def search(text)
      text.split.inject(scoped({:include => [:conversation, :author, :subject]})) do |scope, word|
        scope.scoped :conditions => ["haikus.text like :word or subjects.name like :word", {:word => "%#{word}%"}] 
      end
    end
  
    def find_by_param(param)
      if param =~ /^(\d+)/
        find($1)
      else
        raise ActiveRecord::RecordNotFound
      end
    end

    def global_feed
      active_authors = Author.recently_updated.limit(10)
      where(id: active_authors.map(&:latest_haiku_id)).includes(:conversation, :author).order('id desc')
    end
  end
  
  
  VALID_SYLLABLES = [5, 7, 5]
  
  def valid_syllables?
    if lines.size != VALID_SYLLABLES.size
      errors.add("Need three lines")
    else
      VALID_SYLLABLES.zip(lines).each_with_index do |(expected, line), row|
        syllable_count = line.split.sum(&:syllables)
        if expected =! syllable_count
          errors.add(:base, "line #{row} has #{syllable_count} syllables") 
        end
      end
    end
  end
  
  def subject_name=(name)
    name = name.gsub(/[^\w| ]/, '').chomp.downcase
    if name.blank?
      self[:subject_name] = nil
    else
      self[:subject_name] = name
      self.subject = Subject.find_or_create_by_name(name)
    end
  end

  def lines
    text.split(/\n/)
  end

  def terse
    text.gsub(/\n/, ' / ')
  end

  def to_param
    "#{id}-#{lines.first.parameterize}"
  end
end

app/models/haiku/conversational.rb
module Haiku::Conversational
  def self.included(base)
    base.class_eval do
      belongs_to :conversation

      attr_accessor :conversing_with
      before_create :construct_conversation
      
      after_create do |haiku|
        haiku.conversation.update_attributes(:latest_haiku_update => Time.now) unless haiku.conversation_id.nil?
        Conversation.update_counters(haiku.conversation_id, :haikus_count_total => 1) if haiku.conversation_id
      end
      
      before_destroy do |haiku|
        Conversation.update_counters(haiku.conversation_id, :haikus_count_total => -1) if haiku.conversation_id
      end
    end
  end
  
  def conversing?
    !conversation.nil? && conversation.haikus_count_total > 0
  end
  
  private
    def construct_conversation
      unless conversing_with.nil? || conversing_with.empty?
        other_haiku = Haiku.find(conversing_with)
        connect_with(other_haiku)
        Mailer.conversation_notice(other_haiku, self.author).deliver
      end
    rescue ActiveRecord::RecordNotFound
      # In case the other haiku was deleted while someone was responding to it
    end
  
    def connect_with(other_haiku)
      if other_haiku.conversation.nil?
        other_haiku.create_conversation(:haikus_count_total => 1)
        other_haiku.save!
      end
      self.conversation = other_haiku.conversation
    end
end

app/models/haiku/line.rb
class Line
  attr_reader :words

  def initialize(text)
    @words = text.split
  end

  def syllables
    words.sum(&:syllables)
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  login_filter :only => [:new, :destroy, :update, :email, :deliver]
  
  def create
    if current_author
      @haiku = current_author.haikus.create(params[:haiku])
      redirect_and_flash(@haiku)
    else
      redirect_with_login_context do
        save_deferred_haiku(params[:haiku])
      end
    end
  end

  def index
    respond_to do |f|
      f.html { @haikus = Haiku.recent.page(params[:page]).per(10) }
      f.atom { render_atom(Haiku.recent.limit(10)) }
    end
  end
  
  def search
    if params[:q].present?
      @haikus = Haiku.search(params[:q]).page(params[:page]).per(10)
    end
  end
  
  def show
    @single_haiku = Haiku.find_by_param(params[:id])
  end
  
  def destroy
    haiku = current_author.haikus.find(params[:id])
    haiku.destroy
    flash[:notice] = "Your haiku was deleted"
    respond_to do |f|
      f.html { redirect_to(haiku_path(haiku) == request.referrer ? {controller: 'journal'} : request.referrer) }
      f.js   { head :ok }
    end
  end
  
  private
    def redirect_and_flash(haiku)
      if haiku.conversing_with
        flash[:notice] = "Your haiku started a conversation."
        redirect_to(haiku.conversation)
      else
        flash[:notice] = "Your haiku has been created"
        redirect_to(:back)
      end
    end
end

app/helpers/haikus_helper.rb
module HaikusHelper
  # options include:
  #   conversing_with - The haiku that this creation is in reference too
  #   conversation - An existing conversation that this haiku is being added to
  #   inspire - Show the inspiration upload/image options
  def render_create(options = {})
    render :partial => "haikus/create", :locals => options
  end

  def enter_conversation_link(haiku)
    polymorphic_path = haiku.conversing? ? haiku.conversation : haiku
    link_tag = link_to("Respond", polymorphic_path, :class => "icon reply")
    content_tag(:div, link_tag, :class => "action")
  end
  
  def destroy_haiku_link(haiku)
    if haiku.author == current_author
      link_tag = link_to('Delete', haiku, :method => :delete, :class => 'icon trash')
      content_tag(:div, link_tag, :class => "action")
    end
  end
  
  def haiku_text_tag(options = {})
    options.reverse_merge!(
      autocomplete: 'off',
      rows: 3,
      id: "haiku_text",
      name: "haiku[text]",
      class: "empty")

    text_area_tag(:text, "", options)
  end  
end

app/views/haikus/_create.html.haml
#haiku_form
  = form_for :haiku, :url => {:controller => 'haikus', :action => 'create'} do |form|
    - unless local_assigns[:conversing_with].nil?
      = hidden_field_tag('haiku[conversing_with]', conversing_with.id)
    #conversation_id_wrapper
      - unless local_assigns[:conversation].nil?
        = hidden_field_tag('haiku[conversation_id]', conversation.id)

    %table.internals
      %tr
        %td
        %td#preview{:class => 'empty'}
          %div five syllables
          %div seven syllables
          %div five syllables
      %tr
        %td
          %label="Haiku:"
        %td
          = haiku_text_tag

      %tr
        %td
          %label="Subject:"
        %td
          = text_field_tag 'haiku[subject_name]'
      %tr
        %td
        %td
          = form.submit "Create", :id => "commit_haiku", :disabled => true

  - if local_assigns[:inspire]
    #inspire
      = render 'haikus/inspire'
  

%script
  new Haiku.PeriodicalUpdater("#haiku_text", "#preview", "#commit_haiku");

app/views/haikus/_haiku.html.haml
= div_for(haiku) do
  .avatar_and_time
    .time= haiku.created_at.strftime("%d %b %y")
    = link_to author_path(haiku.author.username) do
      = medium_avatar_image(haiku.author)
  .text_author_group
    = link_to haiku, :class => 'text' do
      - haiku.lines.each do |line|
        .line= line
    .info
      = link_to haiku.author.username, author_path(haiku.author.username), {:class => 'author'}
      - unless haiku.subject_name.nil?
        about
        = link_to_subject(haiku.subject)
  - if haiku.conversation
    .context
      = link_to haiku.conversation do
        - if haiku.conversation.inspiration
          = image_tag haiku.conversation.inspiration.small, :class => 'haiku-inspiration'
        - else
          Conversing with
          .summary= (haiku.conversation.haikus_count_total - 1)
          other haiku
  - if current_author
    .actions
      = enter_conversation_link(haiku)
      = destroy_haiku_link(haiku)

app/views/haikus/_inspire.html.haml
%p#cancel_line{:style => "display:none"}= link_to("cancel", nil, :id => "cancel_link")

#inspiration_what
  You can add an image to your haiku.

#inspiration_selection
  %p= link_to("Use an image", nil, :id => "use_flickr")

#inspiration_preview{:style => "display: none;"}
  = link_to("< Prev", "#", :id => "prev_inspiration")
  = link_to("Next >", "#", :id => "next_inspiration")
  #inspiration_image

#upload_inspiration_image

%script= raw("inspirations(#{inspirations_json});")

app/views/haikus/index.html.haml
- rss_discovery "Everyone's haikus", haikus_path

- title "Everyone's haiku"
%h2 Everyone's haiku

= render @haikus

= paginate @haikus, id: 'pagination'

app/views/haikus/search.html.haml
- title "Search haiku"

%h2 Search haiku
= form_tag({:controller => 'haikus', :action => 'search'}, {:method => :get}) do
  = text_field_tag("q", params[:q])
  = submit_tag("Search")

- if @haikus
  = render @haikus
  = paginate @haikus, :id => 'pagination', :previous_label => '< Prev', :next_label => 'Next >', :page_links => false

%script $('q').focus()

app/views/haikus/show.html.haml
- title "A haiku by #{@single_haiku.author.username}"
- description @single_haiku.text.gsub(/\n/, ' / ')

%h2
  A haiku by
  = link_to @single_haiku.author.username, author_path(@single_haiku.author.username)

.center
  - if @single_haiku.conversing? && @single_haiku.conversation.inspiration
    .haiku-inspiration
      = link_to @single_haiku.conversation, :class => "" do
        = image_tag @single_haiku.conversation.inspiration.thumbnail
      %br
      = link_to @single_haiku.conversation do
        = "#{@single_haiku.conversation.haikus_count_total} haiku"
        are inspired by this image
  .haiku-big
    .text
      - @single_haiku.lines.each do |line|
        .line= line
    .info
      = "Created on #{@single_haiku.created_at.strftime("%b %d, %Y")} by"
      = link_to_author @single_haiku.author
    - if @single_haiku.subject_name
      .info
        Subject:
        = link_to_subject @single_haiku.subject_name
    - if current_author
      .actions
        = destroy_haiku_link(@single_haiku)
 
.conversation-section
  - if @single_haiku.conversing? && !@single_haiku.conversation.inspiration
    This haiku is in a conversation with
    = "#{@single_haiku.conversation.haikus_count_total} haiku."
    = link_to "Post your own haiku »", @single_haiku.conversation, {:style => "font-weight: bold;"}
    = render @single_haiku.conversation.haikus
  - elsif !@single_haiku.conversing?
    %h3 Start a conversation with this haiku:
    #statement_form
      = render_create(:conversing_with => @single_haiku)