config/routes.rb
HaikuVillage::Application.routes.draw do
  resources :authors do
    member do
      get :friends
    end

    resources :subjects, controller: 'authors/subjects'
  end
  match 'signup' => 'authors#new', as: 'signup'

  match 'autocomplete/subject' => 'subjects#autocomplete'

  resources :subjects do
    collection do
      get :suggest
    end
  end

  resources :haikus, path: 'haiku' do
    collection do
      get :search
    end
  end

  resources :conversations
  resources :messages
  resources :friends
  resources :favorites

  resources :password_resets, path: 'forgot'

  controller 'public' do
    match 'about' => :about, as: :about
    match 'register' => :register, as: :register
    match 'feedback' => :feedback, as: :feedback
  end

  resource :session

  controller 'sessions' do
    match 'login' => :new, as: 'login'
    match 'logout' => :destroy, as: 'logout'
  end

  match   'settings(/:action)' => 'profile', as: :profile
  match   'journal(/:action)' => 'journal', as: :journal

  match 'google_gadget' => 'public#google_gadget', defaults: { format: 'xml' }, as: 'google_gadget'
  match 'syllables' => 'syllables#index'

  root to: 'public#index'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  login_filter

  def index
    @following = current_author.following.recently_updated
  end

  def update
    @author = Author.find_by_username!(params[:id])
    current_author.friends << @author
    Mailer.new_friend(@author.email, current_author).delive
  end
  
  def destroy
    @author = Author.find_by_username!(params[:id])
    Friendship.destroy_all(:author_id => current_author, :friend_id => @author)
    respond_to do |f|
      f.js
      f.html do
        flash[:notice] = "#{@author.username} removed from friends"
        redirect_to :back
      end
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
  # options:
  #  <tt>show_actions</tt> - Show add/remove friend and send message. Defaults to false
  def render_friends(friends, locals = {})
    locals.reverse_merge!(:show_actions => false)
    render partial: 'friends/friend', collection: friends, locals: locals
  end
  
  def add_friend(friend)
    options = {method: :put, id: 'add-friend', remote: true}
    options[:style] = 'display:none;' if current_author.following.include?(friend)
    button_to("+ Follow", friend_path(friend.username), options)
  end

  def remove_friend(friend)
    options = {method: :delete, id: 'remove-friend', remote: true}
    options[:style] = 'display:none;' unless current_author.following.include?(friend)
    button_to("Following", friend_path(friend.username), options)
  end
  
  def remove_friend_thumbnail(friend)
    link_to("Remove",
      friend_path(friend.username),
      {:method   => :delete, :confirm  => "Are you sure?"})
  end
end

app/views/friends/_friend.html.haml
.friend{:id => dom_id(friend)}
  .avatar
    = link_to author_path(friend.username) do
      = large_avatar_image(friend)
  .details
    .username_and_actions
      .username
        = link_to friend.username, author_path(friend.username)
        has written
        = "#{friend.haikus_count_total} haiku"
      - if show_actions
        .actions
          = link_to "Send message", messages_path(:friend => friend.id)
          |
          = remove_friend_thumbnail(friend)
    - unless friend.latest_haiku_id.nil?
      .latest_haiku
        .latest_haiku_text
          = "\"#{friend.latest_haiku.terse}\""
        .latest_haiku_time
          = "#{distance_of_time_in_words(friend.latest_haiku.created_at, Time.now)} ago"

app/views/friends/_layout.html.erb
<% title 'Your friends' %>
<h2>Friends</h2>

<%= sub_menu(:class => "submenu_items") do |m| %>
  <% if current_author %>
    <%= m.link "Your friends", friends_path %>
  <% end %>
  <%= m.link "Find authors", authors_path %>
<% end %>

<div class="submenu_content">
  <%= yield %>
</div>

app/views/friends/index.html.erb
<%= render layout: 'layout' do %>
  <% if @following.any? %>
    <%= render_friends(@following, show_actions: true) %>
  <% else %>
    <div class="empty_list">
      Make some new friends! Find an <%= link_to "author", authors_path %> that's interesting and add them to your friends list.
    </div>
  <% end %>
<% end %>