config/routes.rb
HaikuVillage::Application.routes.draw do
  resources :authors do
    member do
      get :friends
    end

    resources :subjects, controller: 'authors/subjects'
  end
  match 'signup' => 'authors#new', as: 'signup'

  match 'autocomplete/subject' => 'subjects#autocomplete'

  resources :subjects do
    collection do
      get :suggest
    end
  end

  resources :haikus, path: 'haiku' do
    collection do
      get :search
    end
  end

  resources :conversations
  resources :messages
  resources :friends
  resources :favorites

  resources :password_resets, path: 'forgot'

  controller 'public' do
    match 'about' => :about, as: :about
    match 'register' => :register, as: :register
    match 'feedback' => :feedback, as: :feedback
  end

  resource :session

  controller 'sessions' do
    match 'login' => :new, as: 'login'
    match 'logout' => :destroy, as: 'logout'
  end

  match   'settings(/:action)' => 'profile', as: :profile
  match   'journal(/:action)' => 'journal', as: :journal

  match 'google_gadget' => 'public#google_gadget', defaults: { format: 'xml' }, as: 'google_gadget'
  match 'syllables' => 'syllables#index'

  root to: 'public#index'
end

app/views/404/author.html.erb
<%- title 'Author does not exist' %>

<h2>Author <%= params[:id] %> does not exist</h2>

<p>
  This author may have changed usernames.
  You can also try <%= link_to 'searching for authors', authors_path %>.
</p>

app/views/404/conversation.html.erb
<%- title 'Conversation not found' %>

<h2>We could not find this conversation</h2>

<p>
  <%= link_to 'Take me back', conversations_path %> to the list of all conversations.
</p>

app/views/404/haiku.html.erb
<%- title 'This haiku does not exist' %>

<h2>This haiku no longer exists. The author may have deleted it.</h2>

app/views/404/subject.html.erb
<%- title 'Subject does not exist' %>

<h2>There are no haiku about <%= params[:id] %></h2>

<p>
  Be the first to write about <%= params[:id] %> in
  <%= link_to 'your journal', journal_path %>.
</p>