config/routes.rb
HaikuVillage::Application.routes.draw do
  resources :authors do
    member do
      get :friends
    end

    resources :subjects, controller: 'authors/subjects'
  end
  match 'signup' => 'authors#new', as: 'signup'

  match 'autocomplete/subject' => 'subjects#autocomplete'

  resources :subjects do
    collection do
      get :suggest
    end
  end

  resources :haikus, path: 'haiku' do
    collection do
      get :search
    end
  end

  resources :conversations
  resources :messages
  resources :friends
  resources :favorites

  resources :password_resets, path: 'forgot'

  controller 'public' do
    match 'about' => :about, as: :about
    match 'register' => :register, as: :register
    match 'feedback' => :feedback, as: :feedback
  end

  resource :session

  controller 'sessions' do
    match 'login' => :new, as: 'login'
    match 'logout' => :destroy, as: 'logout'
  end

  match   'settings(/:action)' => 'profile', as: :profile
  match   'journal(/:action)' => 'journal', as: :journal

  match 'google_gadget' => 'public#google_gadget', defaults: { format: 'xml' }, as: 'google_gadget'
  match 'syllables' => 'syllables#index'

  root to: 'public#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  include Author::Authenticated
  include Author::Friendly
  include Author::Remembered
  include Author::Bipolar

  has_many :favorites
  has_many :favorite_haikus, :through => :favorites, :source => :haiku
  has_many :haikus
  has_many :messages
  has_many :subjects, through: :haikus
  belongs_to :latest_haiku, :class_name => "Haiku"
  
  before_validation :if => :username do |author|
    author.username = author.username.downcase
  end

  scope :brand_new, :order => 'created_at desc'
  scope :active, :order => 'haikus_count_week desc, haikus_count_total desc', :conditions => 'haikus_count_total > 0'
  scope :popular, :order => 'favorited_count_total desc', :conditions => 'favorited_count_total > 0'
  scope :recently_updated, where('latest_haiku_id is not null').order('latest_haiku_id desc')
  
  validates_presence_of :email, :username
  validates_uniqueness_of :username, :email
  validates_format_of :username, :with => /\A[a-z0-9]+\Z/i, :message => 'can only contain numbers and letters', :on => :create
  
  def subject_summaries
    records = haikus.where('subject_id is not null').order('count_all desc').group(:subject_id).count
    records.map do |(subject_id, haiku_count)|
      [Subject.find(subject_id), haiku_count]
    end
  end
  
  private
    def downcase_username
      self.username = self.username.downcase unless self.username.nil?
    end
end

app/models/author/authenticated.rb
require 'digest/sha1'

module Author::Authenticated
  extend ActiveSupport::Concern

  included do
    before_save :encrypt_password

    attr_accessor :password
    attr_protected :hashed_password, :salt

    validates_presence_of   :password, on: :create, unless: :fb_uid
    validates_presence_of   :password, on: :update, unless: Proc.new { |user| user.password.nil? }
  end
  
  module ClassMethods
    def find_by_login!(login)
      find_by_login(login) || (raise ActiveRecord::RecordNotFound)
    end

    def find_by_login(login)
      send(login =~ /@/ ? :find_by_email : :find_by_username, login)
    end

    def authenticate(login, password)
      if (author = find_by_login(login)) && author.authenticate(password)
        author
      end
    end

    def encrypted_password(password, salt)
      string_to_hash = password + "haiku" + salt
      Digest::SHA1.hexdigest(string_to_hash)
    end
  end
  
  def authenticate(pwd)
    return false unless pwd.is_a?(String) && !hashed_password.nil?
    self.hashed_password == self.class.encrypted_password(pwd, self.salt)
  end

  private
    def encrypt_password
      return if password.nil?
      self.salt = SecureRandom.base64(16)
      self.hashed_password = self.class.encrypted_password(self.password, self.salt)
      self.password = nil
    end
end

app/models/author/bipolar.rb
class Author
  module Bipolar
    extend ActiveSupport::Concern

    module ClassMethods
      def find_unique_username(email)
        original = email.gsub(/\@(.*)/, '').gsub(/[^A-Za-z0-9]/, '')
        username = original
        i = 0

        until where(username: username).empty?
          i += 1
          username = "#{original}#{i}"
        end

        username
      end

      def find_or_create_by_facebook(fb_uid, graph)
        facebook_author = find_or_initialize_by_fb_uid(fb_uid)

        if facebook_author.persisted?
          facebook_author
        else
          data = graph.get_object('me')

          if existing_author = Author.find_by_email(data['email'])
            existing_author.update_attribute(:fb_uid, fb_uid)
            existing_author
          else
            facebook_author.update_attributes(
              username: find_unique_username(data['email']),
              email: data['email'],
            )
            facebook_author
          end
        end
      end

      def migrate(existing_author, other_author)
        other_author.haikus.each do |haiku|
          existing_author.haikus << haiku
        end

        other_author.messages.each do |message|
          message.update_attribute(:sender, existing_author) if message.sender == other_author
          message.update_attribute(:recipient, existing_author) if message.recipient == other_author
          existing_author.messages << message
        end
        Message.where(sender_id: other_author).delete_all
        Message.where(recipient_id: other_author).delete_all

        other_author.favorites.each do |favorite|
          unless existing_author.favorites.exists?(haiku_id: favorite.haiku_id)
            existing_author.favorites << favorite
          else
            favorite.destroy
          end
        end

        other_author.friendships.each do |friendship|
          unless existing_author.friendships.exists?(friend_id: friendship.friend_id)
            existing_author.friendships << friendship
          else
            friendship.destroy
          end
        end

        other_author.reverse_friendships.each do |friendship|
          unless existing_author.reverse_friendships.exists?(author_id: friendship.author_id)
            existing_author.reverse_friendships << friendship
          else
            friendship.destroy
          end
        end

        other_author.destroy
        existing_author.update_attribute(:fb_uid, other_author.fb_uid)
      end
    end
  end
end

app/models/author/friendly.rb
module Author::Friendly
  extend ActiveSupport::Concern

  included do
    # The authors this author is following
    has_many :friendships
    has_many :following, through: :friendships, :class_name => 'Author', :source => :friend

    has_many :reverse_friendships, :foreign_key => :friend_id, :class_name => 'Friendship'
    has_many :followers, through: :reverse_friendships, :class_name => 'Author'
    
    has_many :friends, :through => :friendships, :class_name => 'Author', :source => :friend, :conditions => {'friendships.mutual' => true}
  end
  
  def mutual?(other_author)
    friends.include?(other_author)
  end

  def feed
    Haiku.recent.where(author_id: [self.id] + following_ids)
  end
end

app/models/author/remembered.rb
module Author::Remembered
  def remember_me!
    self.remember_token = SecureRandom.base64(32)
    save(validation: false)
  end
  
  def forget_me!
    self.remember_token = nil
    save(validation: false)
  end
end

app/controllers/authors/subjects_controller.rb
class Authors::SubjectsController < ApplicationController
  def index
    @author = Author.find_by_username!(params[:author_id])
    @subjects = @author.subjects
  end

  def show
    @author = Author.find_by_username!(params[:author_id])
    @haikus = @author.haikus.recent.find_all_by_subject_name(params[:id]).page(params[:page]).per(10)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  prevent_logged_in :only => [:new, :create]

  def index
    @active_authors = Author.active.limit(12)
    @new_authors = Author.brand_new.limit(12)
    @popular_authors = Author.popular.limit(40)
  end
  
  def new
    @author = Author.new
  end
  
  def create
    @author = Author.new(params[:author])
    if @author.save
      login(@author)
      redirect_to :controller => "journal"
    else
      render "new"
    end
  end

  def show
    @author = Author.find_by_username!(params[:id])
    
    respond_to do |f|
      f.html do
        @haikus = @author.haikus.recent.page(params[:page]).per(10)
        # :total_entries => @author.haikus_count_total
      end
      f.atom { render_atom(@author.haikus.recent.limit(10)) }
      f.text { render :text => @author.haikus.map{|haiku| haiku.text}.join("\n\n") }
    end
  end
  
  def friends
    @author = Author.find_by_username!(params[:id])
    @friends = @author.friends.recently_updated.includes(haikus: :conversation)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def author_cloud(authors)
    font_sizes = {}
    authors.sort { |author1, author2| author1.favorited_count_total <=> author2.favorited_count_total }.each_with_index do |author, index|
      font_sizes[author.username] = number_to_percentage(80 + (120 * (index.to_f / authors.size)), :precision => 0)
    end
    
    sorted_by_name = authors.sort { |author1, author2| author1.username <=> author2.username }
    
    sorted_by_name.map do |author|
      link_to_author author, {:style => "font-size: #{font_sizes[author.username]}"}
    end.join(' ').html_safe
  end
  
  def author_list(authors)
    authors.map { |author| link_to_author author }.join(', ').html_safe
  end
  
  def link_to_author(author, html_options = {})
    link_to(author.username, author_path(author.username), html_options)
  end  
end

app/views/authors/_search_form.html.erb
<%= form_tag authors_path, method: :get, id: 'author_search' do %>
  <%= text_field :author, :username, name: 'q', value: params[:q], size: 10 %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<script>$('#author_username').focus()</script>

app/views/authors/_show_layout.html.erb
<%- rss_discovery "#{@author.username}'s haiku", author_path(@author.username) %>
<%- title "#{@author.username}'s Journal" %>
<% description "Haiku by #{@author.username}" %>

<div class="author-header">
  <div class="avatar">
    <%= large_avatar_image(@author) %>
  </div>
  <div class="nav">
    <div class="header">
      <h2><%= "#{@author.username}'s Journal" %></h2>
      <% if current_author %>
        <%= add_friend(@author) %>
        <%= remove_friend(@author) %>
        <form>
          <input type="submit" value="Message" id="new-message" />
        </form>
      <% end %>
    </div>

    <%= sub_menu(:class => "submenu_items") do |m| %>
      <%= m.link "Haiku", author_path(id: @author.username) %>
      <%= m.link "Subjects", author_subjects_path(author_id: @author.username)  %>
      <%= m.link "Friends", friends_author_path(@author.username)  %>
    <% end %>
  </div>
</div>

<div class="submenu_content author_content">
  <%= yield %>
</div>

<div id="message-dialog">
  <%= form_for :message, url: messages_path, html: {style: "margin-bottom: 10px;", id: 'haiku_form'} do |form| %>
    <%= hidden_field_tag 'message[recipient_id]', @author.id %>
    <table class="internals">
      <tr>
        <td />
        <td id="preview", class="empty">
          <div>Start typing a haiku below and your</div>
          <div>syllables will be counted here.</div>
          <div></div>
        </td>
      </tr>
      <tr>
        <td><label>Message:</label></td>
        <td><%= haiku_text_tag(:name => "message[text]", :id => "message_text") %></td>
      </tr>
      <tr>
        <td />
        <td>
          <%= form.submit "Send", id: "send_haiku", disabled: true %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

<script>
$(function() {
  new Haiku.PeriodicalUpdater("#message_text", "#preview", "#send_haiku");
  $('#message-dialog').dialog({
    autoOpen: false,
    title: 'Send a message',
    resizable: false,
    width: 460
  });

  $('#new-message').click(function(e) {
    $('#message-dialog').dialog('open');
  	e.preventDefault();
  })
});
</script>

<script>
$(function() {
  $('#add-friend').click(function() {
    $(this).hide();
    $('#remove-friend').show();
  });

  $('#remove-friend')
    .click(function() {
      $(this).hide();
      $('#add-friend').show();
    })
    .hover(
      function() {
        $(this).attr('value', 'X Unfollow')
      },
      function() {
        $(this).attr('value', 'Following')
      }
    );
});
</script>

app/views/authors/_tiny.html.erb
<div class="author">
  <% link_to author_url(tiny.username) do %>
    <%= image_tag small_avatar_url(tiny) %>
  <% end %>
  <%= link_to tiny.username, author_url(tiny.username) %>
</div>

app/views/authors/forgot.html.erb
<% title 'Forget your password?' %>

<h2>Forget your password? Type in your username or email.</h2>
<% form_tag do %>
  <table>
    <tr>
      <td><%= label_tag :login, "Username or email:" %></td>
      <td><%= text_field_tag :login %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= submit_tag "Reset my password" %>
      </td>
    </tr>
  </table>
<% end %>

<script>
$('login').focus();
</script>

app/views/authors/friends.html.erb
<%= render :layout => 'authors/show_layout' do %>
  <%= render_friends(@friends) %>
<% end %>

app/views/authors/index.html.erb
<%= render layout: 'friends/layout' do %>
  <%= render "search_form" %>
  <div class="column">
    <h3>Active authors</h3>
    <div class="href_list"><%= author_list(@active_authors) %></div>
  </div>

  <div class="column">
    <h3>New authors</h3>
    <div class="href_list"><%= author_list(@new_authors) %></div>
  </div>

  <div class="cloud">
    <h3>Most popular authors</h3>
    <%= author_cloud(@popular_authors) %>
  </div>
<% end %>

app/views/authors/new.html.haml
- title "New account"

%h2 Create a new account
= form_for @author do |form|
  %table
    %tr
      %td
        = form.label :email, 'Email:'
      %td
        = form.error_message_on :email, :prepend=>"Email "
        = form.text_field :email
      %td{rowspan: "3"} 
        %h2 or
      %td{rowspan: "3"}
        = facebook_login size: 'large', length: 'long'
    %tr
      %td
        = form.label :username, 'Username:'
      %td
        = form.error_message_on :username, :prepend=>"User name "
        = form.text_field :username
    %tr
      %td
        = form.label :password, 'Password:'
      %td
        = form.error_message_on :password, :prepend=>"Password "
        = form.password_field :password  
    %tr
      %td
      %td
        = form.submit 'Register'

    %tr
      %td
      %td{:style => 'padding-top: 10px'}
        = link_to "Are you already an author?", login_path
%script
  document.getElementById('author_email').focus();

app/views/authors/reset_password.html.erb
<h2>Type in your new password</h2>
<% form_tag do %>
  <%= hidden_field_tag :token, @password_reset.token %>
  <table>
    <tr>
      <td><%= label_tag :password, "New password:" %></td>
      <td><%= password_field_tag :password %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= submit_tag "Change password" %></td>
    </tr>
  </table>
<% end %>

<script>
$('password').focus();
</script>

app/views/authors/show.html.erb
<%= render :layout => 'show_layout' do %>
	<%= render @haikus %>
				
	<br />
	<%= paginate @haikus, id: 'pagination' %>

  <%= render 'feed_links' %>
<% end %>